### REGISTER PATIENT

POST http://localhost:4000/patient/auth/register
Content-Type: application/json

{
    "email":  "patient@test.com",
    "password": "patient",
    "name":"Patient Test",
    "imageURL":"Test"
}

### LOGIN PATIENT
POST http://localhost:4000/patient/auth/login
Content-Type: application/json

{
    "email": "patient1@test.com",
    "password":"patient1"
}